### ISSUE TITLE
Need ability to configure timeout time.

### ISSUE THREAD

**Issue by barser** [dmitry-zhuravlev/rest-runner-teamcity-plugin#2]
First calls to http-api after deployment could take some additional time (app initialization, lazy loading etc...). For now I recieve the following error:
	REST call to http://server/api/test failed Read timed out

It seems that timeout is no longer than 20 seconds or like. 

Would you please provide an opportunity to tune its value? Thanks!

**Comment by dmitry-zhuravlev** [comment]
Timeout now present since 1.2.1 version.
